[package]
name = "just_act"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slick = { path = "../slick", version = "0.1.0" }
fxhash = "0.2.1"